version: "3"

services:
  kamailio:
    image: techer/kamailio
    networks:
      main:
        aliases:
          - kamailio
    ports: 
      - 5060:5060/tcp
      - 5060:5060/udp
  
  asterisk_1:
    image: techer/asterisk
    networks:
      main:
        aliases:
          - asterisk_1

  asterisk_2:
    image: techer/asterisk
    networks:
      main:
        aliases:
          - asterisk_2

  ari:
    image: techer/ari
    networks:
      main:
        aliases:
          - ari
    ports:
      - 8080:8080

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'teste'
      MYSQL_PASSWORD: 'teste'
      MYSQL_ROOT_PASSWORD: 'NOUSAR'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      main:
        aliases:
          - db

volumes: 
  my-db:

networks:
  main:
  