version: "3"

networks:
  main:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  
  asterisk:
    image: techer/asterisk
    networks:
      main:
        aliases:
          - asterisk
        ipv4_address: 172.20.0.8
    ports: 
      - 5060:5060/tcp
      - 5060:5060/udp
      - 10000-10050:10000-10050/udp
      - 10000-10050:10000-10050/tcp

  ari:
    image: techer/ari
    networks:
      main:
        aliases:
          - ari

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'teste'
      MYSQL_PASSWORD: 'teste'
      MYSQL_ROOT_PASSWORD: 'NOUSAR'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      main:
        aliases:
          - db

  # asterisk_2:
  #   image: techer/asterisk
  #   networks:
  #     main:
  #       aliases:
  #         - asterisk_2

  

  # kamailio:
  #   image: techer/kamailio
  #   networks:
  #     main:
  #       aliases:
  #         - kamailio
  #       ipv4_address: 172.20.0.9
  #   ports: 
  #     - 5060:5060/tcp
  #     - 5060:5060/udp

  # db_kamailio:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'kamailio'
  #     MYSQL_USER: 'kamailio'
  #     MYSQL_PASSWORD: 'kamailio'
  #     MYSQL_ROOT_PASSWORD: 'NOUSAR'
  #   volumes:
  #     - my-db_kamailio:/var/lib/mysql
  #   networks:
  #     main:
  #       aliases:
  #         - db_kamailio

volumes: 
  my-db:
  # my-db_kamailio:
