FROM node:17-alpine

#RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

#USER node

RUN apk update && apk add bash && apk add --no-cache coreutils

WORKDIR /home/node/app

#COPY --chown=node:node ./ari-app/package*.json ./

#RUN npm install

#COPY --chown=node:node ./ari-app .

EXPOSE 8080

ADD wait-for-it.sh /wait-for-it.sh

RUN ["chmod", "+x", "/wait-for-it.sh"]

ENTRYPOINT ["/wait-for-it.sh", "asterisk:8088", "-t", "60" , "--", "npx", "nodemon", "-L", "app.js"]