FROM node:17-alpine

#RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

#USER node

WORKDIR /home/node/app

#COPY --chown=node:node ./ari-app/package*.json ./

#RUN npm install

#COPY --chown=node:node ./ari-app .

EXPOSE 8080

ENTRYPOINT ["npx", "nodemon", "-L", "app.js"]